[package]
name = "serde_json_path_macros_internal"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
path = "mod.rs"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
