[package]
name = "serde_json_path"
version = "0.3.1"
edition = "2021"
license = "MIT"
description = "Parse serde_json Values using JSONPath queries"
documentation = "https://docs.rs/serde_json_path"
repository = "https://github.com/hiltontj/serde_json_path"
readme = "README.md"
keywords = ["json", "jsonpath", "json_path", "serde", "serde_json"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.38"
