[package]
name = "serde_json_path"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Parse serde_json Values using JSONPath queries"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0.38"
