[workspace]
members = [
    "serde_json_path",
    "serde_json_path_core",
    "serde_json_path_macros",
    "serde_json_path_macros/src/internal"
]

[profile.dev]
incremental = false

[profile.release]
codegen-units = 1
