[package]
name = "serde_json_path_core"
version = "0.1.0"
edition = "2021"

[lib]

[features]
default = []
trace = ["dep:tracing"]

[dependencies]
inventory = { version = "0.3.4" }
once_cell = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tracing = { version = "0.1", optional = true }

[dev-dependencies]
serde_json_path = { path = "../serde_json_path", version = "0.5.3" }
